obj_name_vector: ["cube"] ## table is loaded by default
obj_pos_vector: {cube: {x: 0.65, y: 0.1, z: -0.1}}
obj_orien_vector: {cube: {w: 0.0, x: 0.0, y: 0.0, z: 0.0}}
obj_size_vector: {cube: {x: 0.05, y: 0.05, z: 0.05}}