object_name_vector: ["table", "cube"]
object_pos_vector: {cube: {pose: {x: 0.65, y: 0.1, z: -0.1}, orientation: {w: 0.0, x: 0.0, y: 0.0, z: 0.0}}, table: {pose: {x: 0.7, y: 0, z: -0.93}, orientation: {roll: 0, pitch: 0, yaw: 1.5707}}}